[WIP] Update Stepper
beefyfinance/beefy-v2 pull request #1025
Opened 2022-08-29 02:11 UTC by erenjaegar77

Move  stepper into a new reducer to see tx status across app

- [ ] New Reducer/ Actions/ Selectors

- [ ] Update components 

- [ ] Update how manage progress bar styles

2022-09-30 03:29 UTC, seguido requested changes

2022-09-30 03:29 UTC, seguido commented on src/components/Stepper/components/Content/Content.tsx
> +    <>
This logic appears weird if currentData.step is false we show the button, if it is true we also show it but only if bridgeStatus is true as well. 
`currentStepData.step !== 'bridge' || bridgeStatus === 'success' ? <button> : null`

2022-09-30 03:29 UTC, seguido commented on src/components/Stepper/components/Title/Title.tsx
> +
what's with all the spacing? 👀

2022-09-30 03:29 UTC, seguido commented on src/features/data/actions/wallet-actions.tsx
> +      { spender: contractAddr, amount: balanceAmount, token },
this no longer passes in the same amount, are you sure of what you are passing in as balance?

2022-09-30 03:29 UTC, seguido commented on src/features/data/actions/wallet-actions.tsx
> +      { spender: contractAddr, amount: boostAmount, token },
Same applies here

2022-09-30 03:29 UTC, seguido commented on src/features/vault/components/BoostWidget/Stake/Stake.tsx
> +                className={classes.btnSubmit}
These are still a nightmare of conditions that make it really hard to follow

2022-09-30 03:29 UTC, seguido commented on src/features/vault/components/BoostWidget/Unstake/Unstake.tsx
> +                  className={classes.btnSubmit}
Same, this are a pain to go through

2022-09-30 03:29 UTC, seguido commented on src/features/vault/components/MinterCards/MintBurnCard/components/Burn.tsx
> +        <div className={classes.balances}>
Probably not in scope here, but since it's been reformatted I see it as well haha but this is a immense component

2022-09-30 03:29 UTC, seguido commented on src/components/Stepper/components/Content/Content.tsx
> +    ? t(`${currentStepData.step}-Success-Content`, {
We get many conditions being checked on several components which make it super hard to know what the outcome of a give state would be

2022-09-30 05:37 UTC, erenjaegar77 commented on src/features/vault/components/BoostWidget/Stake/Stake.tsx
> +                className={classes.btnSubmit}
This, and unstake, can be avoided, due in #1089 this components are deleted

2022-09-30 05:44 UTC, erenjaegar77 commented on src/features/data/reducers/wallet/stepper.ts
> +    rewards?: { token: TokenEntity; amount: BigNumber };
@seguido about the comments on wallet-actions for changing the balance  to show the correct amount on claim-unstake from boosts and claim-withdraw from gov vaults, i added this to show the correct token and balance of the rewards 
<img width="410" alt="image" src="https://user-images.githubusercontent.com/88328748/193198641-a005c682-681a-4119-a262-f6ca0e7958a5.png">

2022-10-11 16:50 UTC, seguido approved these changes

2022-10-11 20:41 UTC, merged