Added Shareable URLs #1210
beefyfinance/beefy-v2 pull request #1211
Opened 2022-12-15 03:11 UTC by NauCode

### Main Changes:
- Added several hooks to manage the sync between the Vault Filters in Redux and the URL. It can be customized so we can easily change the URL keys, and it can also be extended to work with other Redux vars.

### Extra Changes:
In the development process, I found a few potential invalid states when some of those vault filters were invalid, so I added some code to keep the app running even on those null/undefined states. I also added a .gitignore rule to the `/.yarn/` folder since it is a local cache.

No new dependencies were added and every new file is type safe.

2022-12-15 09:23 UTC, prevostc commented
hi there! wow, that's a lotta work in not a lot of time,thank you for this ser 🫡

To get straight to the feedback, I'm afraid the approach is a bit off, redux should be the source of truth for the rest of the app (that's his main goal in fact) and you should be finding a way to sync the redux state with the url. Ie: dispatch smth when the uri changes, or the pages inits, and the other way around syncing the url when the user changes his filters. 
Since this is considered by redux to be a side effect, the redux way would be to create a middleware. If everything goes well, you should have left the components untouched.

2022-12-15 11:19 UTC, NauCode commented
Thanks, @prevostc ! I am not sure if I am missing something, but I did it with Redux as the source of truth in mind. For example, let's take the file called "src/hooks/useSyncedVaultStringKey.tsx".

There are two useEffects in there. The first one will trigger only when the Redux state changes (the rest of the effect dependencies are due to being used in the effect and asked by the linter to be added). It will then update the URL with the new Redux state.

The second useEffect is to do the opposite case. What if the user got their filtered URL and shared it with friends? Then their friends will load the URL, and we need to update the filters with those URL parameters (if not, there wouldn't be a way to display the filters from the URL in the fresh loaded page). So in this second case, we parse the URL params and update Redux based on that.

The little changes outside (like the one you mention in https://github.com/beefyfinance/beefy-v2/blob/cf0c2391b9f5f152d4f8efb087ea30a87956d5d1/src/features/data/reducers/filtered-vaults.ts#L22) are done no by necessity but to provide more safety against weird states, but in fact, those changes could be removed if you don't feel comfortable with them being there since those weird states can only happen when developing and hot reloading the app (and not due to my changes but in really particular cases).

I liked this option more than the middleware because I could target it to work in only specific pages by only adding the hooks to those pages (like I did adding it only to the Home page). Still, it is ok, with all of these being said, I will start rewriting it as a redux middleware.

2022-12-15 11:23 UTC, NauCode commented
My only question with the Redux middleware is, is there any way to handle the case I handle in the second useEffect? Because the Redux middleware seems like will easily allow based on the new state of the filters, to update the URL.

But we also need to update the filters if the URL changes (if not, as I said, friends of the user sharing the URL won't be able to see the filters applied with the filtered URL).

And I am not sure if with the Redux middleware is possible to achieve it.

2022-12-15 18:47 UTC, prevostc commented on src/features/data/middlewares/urlSync.ts
> +            // since we can not just compare arrays with ===
you might benefit from lodash `isEqual` here. it performs deep equality. So maybe that could replace `areArraysEqual` too

2022-12-15 18:47 UTC, prevostc commented on src/features/data/middlewares/urlSync.ts
> +      return _baseCondition && syncItem.customExtraActionCondition(action.payload);
You may want to rely on the updated state instead of the action payload here, that could simplify a lot.
Something along the lines of 

```typescript
function filtersToUrl(filterState: FilteredVaultsState): UrlSearchParams { 
  // <very simple serialization to url params, or string maybe>
}

const syncVaultFiltersToUrlMiddleware = next => action => {
  // <if it's a filter action>
  const res = next(action);
  const params = filtersToUrl(<get the updated filter state>);
  // <do the sync here>
}
```

2022-12-15 18:47 UTC, prevostc commented on src/features/data/middlewares/urlSync.ts
> +      return _baseCondition && syncItem.customExtraActionCondition(action.payload);
You would also benefit from smaller helpers based on the type like 
```typescript
const arrayToParam = (arr: string[]): string  => arr.join(",");
const paramToArray = (param: string): string[]  => arr.split(",");
```

2022-12-16 00:00 UTC, NauCode commented
Changes from the previous version:
- Way more simple the code
- It works in hash and browser routers (I found that the previous version was failing when switching to the browser router :( )
- It shows the chain.id in the URL
- Still 0 extra dependencies
- Added some helper functions to clean the code

2022-12-16 00:08 UTC, prevostc commented on src/features/data/middlewares/urlSync.ts
> +    next(action);
I think it's important to return the value of next, can't remember why though 😅 https://redux.js.org/understanding/history-and-design/middleware#seven-examples

2022-12-16 01:08 UTC, NauCode commented on src/features/data/middlewares/urlSync.ts
> +    next(action);
In the code, if you change it to be like:
```typescript
if (action.type === 'filtered-vaults/reset') {
      //next(action);
      updateURL(getURLWithParams());
      return next(action);
    }

    // next(action);

    const newURL = filtersToUrl({
      filterState: store.getState().ui.filteredVaults,
      chainsById: store.getState().entities.chains.byId,
    });
    updateURL(newURL);
    return next(action);
```

Everything breaks, I think because when the URL updates, triggers the other middleware, and it tries to update the state, so both state updates collide. So I kept the code like it is now since everything worked fine.

2023-01-31 01:17 UTC, ReflectiveChimp requested changes
The url needs to overwrite all local storage filters, for example `platformId=apeswap&chains=bsc` needs to set platform and chains, and also set all other values to default. Otherwise if you have some other filter set it will still apply; for example if you have metis + stablecoins category filter set and visit that url, you'll end up with `platformId=apeswap&chains=bsc&vaultCategory=stable`.

Can you also please solve the merge conflicts and perhaps look at de-duplicating some of the code (an example might be using a loop to handle all the booleans)

2024-10-30 11:52 UTC, closed without merging