[FEAT] Add LSD category filters
beefyfinance/beefy-v2 pull request #1429
Opened 2023-04-11 23:18 UTC by erenjaegar77

2023-04-12 08:22 UTC, roman-monk commented
would you rather make it "NO-IL" excluding stables?
there are many similar vaults not included here like WBTC-multiBTC/renBTC/sBTC, sETH-ETH, alETH-ETH

2023-04-17 18:35 UTC, seguido requested changes

2023-04-17 18:35 UTC, seguido commented on src/locales/en/main.json
> +  "Filter-CatgryNoIL": "Correlated",
let's remove NOIL mentions and talk about correlated

2023-04-17 19:38 UTC, seguido approved these changes

2023-04-17 20:25 UTC, merged