[FIX] Claim action text
beefyfinance/beefy-v2 pull request #907
Opened 2022-07-05 23:47 UTC by erenjaegar77

update types for claim actions and update with a correct text

2022-07-06 19:12 UTC, seguido requested changes

2022-07-06 19:12 UTC, seguido commented on src/components/Steps/Steps.tsx
> +    steps.finished && steps.items[steps.currentStep].step === 'claim-boost';
do we need to check for steps finished?

2022-07-06 19:12 UTC, seguido commented on src/components/Steps/Steps.tsx
> +    steps.finished && steps.items[steps.currentStep].step === 'claim-boost';
the entire component works comparing steps.items[xxx], maybe this var isn't useful and this comparison can be done below

2022-07-06 19:12 UTC, seguido commented on src/components/Steps/Steps.tsx
> +                          isClaimBoostAction ? 'Transactn-Claimed-Boost' : 'Transactn-Claimed-Gov',
So here, just compare step to claim-boost

2022-07-07 22:47 UTC, erenjaegar77 commented on src/components/Steps/Steps.tsx
> +    steps.finished && steps.items[steps.currentStep].step === 'claim-boost';
yes is needed because if steps.finished = false breaks the app

2022-07-07 22:50 UTC, erenjaegar77 commented on src/components/Steps/Steps.tsx
> +                          isClaimBoostAction ? 'Transactn-Claimed-Boost' : 'Transactn-Claimed-Gov',
i didn't do here cause in last pr i did you mentioned to create new variables to do the code more human friendly

2022-07-08 19:37 UTC, seguido approved these changes

2022-07-08 19:37 UTC, merged